# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pLMzzBfQXRkJqHPTDfCSlWwVvKAkXcB
"""

import streamlit as st

# Set the title of the app
st.set_page_config(page_title="Dashboard", layout="wide")

# Sidebar navigation
st.sidebar.title("Dashboard")
page = st.sidebar.radio("Navigation", ["Home", "Hoax Detection", "Upload Data", "Model"])

# Home Page
if page == "Home":
    st.title("Home")
    st.write("Welcome to the Home Page!")

# Hoax Detection Page
elif page == "Hoax Detection":
    st.title("Hoax Detection")
    st.write("This is the Hoax Detection page.")

# Upload Data Page
elif page == "Upload Data":
    st.title("Upload Data")
    st.write("This is the Upload Data page.")

# Model Page
elif page == "Model":
    st.title("Model")
    st.write("This is the Model page.")

# Content for Home Page (as an example)
if page == "Home":
    st.subheader("Data")
    data = {
        "Name": ["Home Decor Range", "Disney Princess Pink Bag 18'", "Bathroom Essentials", "Apple Smartwatches"],
        "Popularity": [45, 29, 18, 25],
        "Sales": [45, 29, 18, 25]
    }

    st.table(data)

# Adding CSS style for better visualization
st.markdown(
    """
    <style>
    .sidebar .sidebar-content {
        background-image: linear-gradient(#2e7bcf,#2e7bcf);
        color: white;
    }
    .css-1aumxhk {
        font-size: 18px;
    }
    </style>
    """,
    unsafe_allow_html=True
)